#!/bin/sh
echo "Starting BusyBox initramfs..."

# Mount essential filesystems
mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t devtmpfs dev /dev
# Mount boot partition (check if device exists)
if [ -e /dev/mmcblk0p1 ]; then
    mount -t vfat /dev/mmcblk0p1 /boot
else
    echo "Boot partition not found!"
fi

# Switch to interactive shell
exec /bin/sh
